language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

before_install:
  - travis_retry pip install codecov

install:
  - travis_retry pip install -U .
  - travis_retry pip install -U -r dev-requirements.txt

before_script:
  - flake8 flask_apispec

script: py.test

after_success:
  codecov
